# Generated by Django 3.2.6 on 2021-08-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_pokemons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokemons',
            new_name='Pokemon',
        ),
    ]
